language: go
dist: bionic
arch:
  - ppc64le
  
go:
  - 1.16.x
  
before_script:
  - git clone https://github.com/srividyac09/activemq-artemis-operator.git
  
script: 
  - go build -v -o operator ./cmd/manager
  - go test -v ./...
  
