language: go
dist: bionic
arch:
  - ppc64le
  
go:
  - 1.16.x
 
tags:
  - 'v0.19.2'
script: 
  - go build -v -o operator ./cmd/manager
  - cd /activemq-artemis-operator/test/utils/config
  - go test 
  
  
